"""Regenerate the Linux/Python 3.12 production lock and dev constraints."""
from pathlib import Path
import re
import shutil
import subprocess


ROOT = Path(__file__).resolve().parents[1]
UV_VERSION = '0.12.19'
TARGET = 'x86_64-unknown-linux-gnu'
HEADER = (
    '# Production dependency resolution: CPython 3.12, Linux x86_64 (glibc).\n'
    '# Not a universal Windows/macOS lock. Validation status: docs/DEPLOYMENT.md.\n'
)


def main():
    uv = shutil.which('uv')
    if uv is None:
        raise SystemExit(f'Install uv=={UV_VERSION} in a separate tooling venv first.')
    version = subprocess.check_output([uv, '--version'], text=True).split()[1]
    if version != UV_VERSION:
        raise SystemExit(f'Expected uv {UV_VERSION}, found {version}.')
    lock = ROOT / 'requirements.lock.txt'
    # Existing runtime pins are hard constraints: incompatible changes fail
    # instead of silently upgrading the dependency graph.
    constraints = ['--constraint', 'requirements.lock.txt'] if lock.exists() else []
    subprocess.run([
        uv, 'pip', 'compile', 'requirements.txt', *constraints,
        '--python-version', '3.12', '--python-platform', TARGET,
        '--generate-hashes', '--no-emit-index-url', '--no-emit-find-links',
        '--custom-compile-command', 'python scripts/compile_requirements.py',
        '--output-file', 'requirements.lock.txt',
    ], cwd=ROOT, check=True)
    content = lock.read_text(encoding='utf-8')
    lock.write_text(HEADER + content, encoding='utf-8')

    pins = []
    for line in content.splitlines():
        line = line.strip()
        if not line or line.startswith(('#', '--hash=')):
            continue
        pin = line.removesuffix('\\').strip()
        if not re.fullmatch(r'[A-Za-z0-9_.-]+==[^\s;\\]+', pin):
            raise SystemExit(f'Unexpected lock entry; review constraints generation: {line}')
        pins.append(pin)
    if not pins:
        raise SystemExit('Refusing to generate empty runtime constraints.')
    (ROOT / 'requirements.constraints.txt').write_text(
        '# Generated by scripts/compile_requirements.py from requirements.lock.txt.\n'
        '# Version-only constraints for dev installation; not a production lock.\n'
        '# Production installations must use requirements.lock.txt with --require-hashes.\n'
        + '\n'.join(pins) + '\n', encoding='utf-8',
    )


if __name__ == '__main__':
    main()
